### ISSUE TITLE
Better Problem Creating User Behavior

### ISSUE THREAD

**Issue by nichujie** [joint-online-judge/cattle#84]
Guide user to add or create problems if there is no problems (go to problem settings)
![image](https://user-images.githubusercontent.com/17191827/150702846-40a1ad40-e719-4c55-9bc8-900c7e04b94b.png)

A shortcut to create new problems on problem settings page.
![image](https://user-images.githubusercontent.com/17191827/150702892-d2ff8c53-badd-4fcf-b815-734cff500686.png)

**Comment by wznmickey** [comment]
Did in https://github.com/joint-online-judge/cattle/pull/125
